"""teste

Revision ID: 657958fd8bee
Revises: ea92bbabfb42
Create Date: 2024-12-27 09:53:31.452611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657958fd8bee'
down_revision = 'ea92bbabfb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings')
    # ### end Alembic commands ###
