"""update expenses

Revision ID: d58ecb9ead3a
Revises: 657958fd8bee
Create Date: 2025-01-01 16:38:33.183095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58ecb9ead3a'
down_revision = '657958fd8bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.drop_column('expense_type')
        batch_op.drop_column('expense_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('expense_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
