"""Recreate all tables

Revision ID: e5331113e5b8
Revises: d58ecb9ead3a
Create Date: 2025-01-01 16:54:45.661020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5331113e5b8'
down_revision = 'd58ecb9ead3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
