"""add status to expenses

Revision ID: 07842dc90bf4
Revises: 
Create Date: 2026-03-16 18:36:22.754643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07842dc90bf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='paid', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
